### ISSUE TITLE
 A few questions about the project

### ISSUE THREAD

**Issue by Alex87a** [Piero24/TelegramBot-AmazonOffers#1]
Good evening! I have some questions about the project:

1) First of all, have you ever encountered the 429 error called "TooManyRequests"? Since these are new channels (at least so it seems to me looking at the ones you inserted in Linktree), you too, like me, should have a very low limit. As a result, Amazon may limit requests. Have you dealt with this before?

2) Would it be possible to have the part of code that deals with image customization? I'm using a Scraper and would like to be able to do something similar.

Thanks in advance!

**Comment by Piero24** [comment]
Hi @Alex87a,

1. The problem `429 error called "TooManyRequests"` often occurs if you have a new channel. It can happen for various reasons. Here you can find an answer I had given some time ago on [stackoverflow](https://stackoverflow.com/a/76180604/8723227).

    In short, if your APIs are new as it seems to me you must first make a sale through your affiliate link for the APIs to be unlocked. The unlock will last for 30 days from the last sale through your link. So if you make a sale today and tomorrow you get access to the APIs, then you're good for 30 days. If in the next 30 days you don't make any sales through your link, then they will be blocked until you make a new sale. If instead you have already made a sale through your affiliate link and more than 24-48 hours have passed and you can view the products through the amazon [scratchpad](https://webservices.amazon.it/paapi5/scratchpad/index.html) but not with the bot, then there may be a problem with the parameter settings.

2. For the image customization part, you can find it [here](https://github.com/Piero24/TelegramBot-AmazonOffers/blob/dc7b184212f8229a9fc0dd07333676d732d01c9c/src/media/image_generator.py). Here it takes the dimensions of the image and performs the necessary operations to apply it to the background image which you can find [here](https://github.com/Piero24/TelegramBot-AmazonOffers/tree/dc7b184212f8229a9fc0dd07333676d732d01c9c/src/media/template). If you want a different background image, just change the file name to `backg-2.jpg` or `backg-3.jpg` with your preferred one. If instead you want to modify the position of the elements in the image, you need to change the values in [image_generator.py](https://github.com/Piero24/TelegramBot-AmazonOffers/blob/dc7b184212f8229a9fc0dd07333676d732d01c9c/src/media/image_generator.py). **Be careful that I use `Pillow==9.5.0` because newer versions have changes that do not make the code work correctly**.
